openapi: "3.0.0"
info:
  title: "BeeOS API"
  description: "API for BeeOS wallet management and activity tracking"
  version: "1.0.0"

servers:
  - url: "/api/v1"
    description: "API v1"

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateWalletRequest:
      type: "object"
      required:
        - "wallet"
      properties:
        wallet:
          type: "string"
          description: "Ethereum wallet address"
    CreateActivityRequest:
      type: "object"
      required:
        - "title"
        - "points"
      properties:
        title:
          type: "string"
          description: "Activity title"
        points:
          type: "integer"
          format: "int64"
          description: "Points amount"
    ActivateCodeRequest:
      type: "object"
      required:
        - "code"
      properties:
        code:
          type: "string"
          description: "Promotional code to activate"
    User:
      type: "object"
      properties:
        wallet:
          type: "string"
          description: "Wallet address"
        points:
          type: "integer"
          description: "Total points"
        createdAt:
          type: "string"
          format: "date-time"
          description: "User creation timestamp"
    Activity:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Activity ID"
        wallet:
          type: "string"
          description: "Wallet address"
        title:
          type: "string"
          description: "Activity title"
        points:
          type: "integer"
          format: "int64"
          description: "Points earned"
        txHash:
          type: "string"
          nullable: true
          description: "Transaction hash"
        createdAt:
          type: "string"
          format: "date-time"
          description: "Activity creation timestamp"
    Achievement:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "Achievement ID"
        wallet:
          type: "string"
          description: "Wallet address"
        title:
          type: "string"
          description: "Achievement title"
        description:
          type: "string"
          description: "Achievement description"
        current:
          type: "integer"
          format: "int64"
          description: "Current progress"
        target:
          type: "integer"
          format: "int64"
          description: "Target to complete achievement"
        createdAt:
          type: "string"
          format: "date-time"
          description: "Achievement creation timestamp"
    CreateMintTrackingRequest:
      type: "object"
      required:
        - "address"
        - "topic"
        - "pointsPerMint"
      properties:
        address:
          type: "string"
          description: "Contract address"
        topic:
          type: "string"
          description: "Event topic hash"
        pointsPerMint:
          type: "integer"
          format: "int64"
          description: "Points awarded per mint"
    CreateStakeTrackingRequest:
      type: "object"
      required:
        - "address"
        - "topic"
        - "pointsPerStake"
      properties:
        address:
          type: "string"
          description: "Contract address"
        topic:
          type: "string"
          description: "Event topic hash"
        pointsPerStake:
          type: "integer"
          format: "int64"
          description: "Points awarded per stake"
    MintTracking:
      type: "object"
      properties:
        address:
          type: "string"
          description: "Contract address"
        topic:
          type: "string"
          description: "Event topic hash"
        pointsPerMint:
          type: "integer"
          format: "int64"
          description: "Points awarded per mint"
        createdAt:
          type: "string"
          format: "date-time"
          description: "Tracking creation timestamp"
    StakeTracking:
      type: "object"
      properties:
        address:
          type: "string"
          description: "Contract address"
        topic:
          type: "string"
          description: "Event topic hash"
        pointsPerStake:
          type: "integer"
          format: "int64"
          description: "Points awarded per stake"
        createdAt:
          type: "string"
          format: "date-time"
          description: "Tracking creation timestamp"

tags:
  - name: "Admin"
    description: "Administrative operations"
  - name: "Wallet"
    description: "Wallet-related operations"
  - name: "Tracks"
    description: "Tracking configuration for mint and stake events"

paths:
  /wallets:
    post:
      tags:
        - "Wallet"
      summary: "Create wallet"
      description: "Creates a new wallet"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWalletRequest"
      responses:
        "201":
          description: "Wallet created successfully"
        "400":
          description: "Bad request - invalid wallet address or missing wallet parameter"
        "500":
          description: "Internal server error"

  /wallets/{wallet}/stats:
    get:
      tags:
        - "Wallet"
      summary: "Get wallet statistics"
      description: "Retrieves statistics for a specific wallet"
      security:
        - BearerAuth: []
      parameters:
        - name: "wallet"
          in: "path"
          required: true
          description: "Wallet address"
          schema:
            type: "string"
      responses:
        "200":
          description: "Wallet statistics retrieved successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Bad request - invalid wallet address"
        "401":
          description: "Unauthorized - missing or invalid JWT token"
        "500":
          description: "Internal server error"

  /wallets/{wallet}/activities:
    get:
      tags:
        - "Wallet"
      summary: "Get wallet activities"
      description: "Retrieves all activities for a specific wallet"
      security:
        - BearerAuth: []
      parameters:
        - name: "wallet"
          in: "path"
          required: true
          description: "Wallet address"
          schema:
            type: "string"
        - name: "page"
          in: "query"
          required: false
          description: "Page number (default: 0)"
          schema:
            type: "integer"
            default: 0
        - name: "size"
          in: "query"
          required: false
          description: "Page size (default: 5, max: 100)"
          schema:
            type: "integer"
            default: 5
            maximum: 100
      responses:
        "200":
          description: "Wallet activities retrieved successfully"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Activity"
        "400":
          description: "Bad request - invalid wallet address"
        "401":
          description: "Unauthorized - missing or invalid JWT token"
        "500":
          description: "Internal server error"
    post:
      tags:
        - "Wallet"
        - "Admin"
      summary: "Create a new activity"
      description: "Creates a new activity for a wallet (admin only)"
      security:
        - ApiKey: []
      parameters:
        - name: "wallet"
          in: "path"
          required: true
          description: "Wallet address"
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateActivityRequest"
      responses:
        "201":
          description: "Activity created successfully"
        "400":
          description: "Bad request - invalid input"
        "401":
          description: "Unauthorized - missing API key"
        "403":
          description: "Forbidden - invalid API key"
        "500":
          description: "Internal server error"

  /wallets/{wallet}/achievements:
    get:
      tags:
        - "Wallet"
      summary: "Get wallet achievements"
      description: "Retrieves all achievements for a specific wallet"
      security:
        - BearerAuth: []
      parameters:
        - name: "wallet"
          in: "path"
          required: true
          description: "Wallet address"
          schema:
            type: "string"
      responses:
        "200":
          description: "Wallet achievements retrieved successfully"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Achievement"
        "400":
          description: "Bad request - invalid wallet address"
        "401":
          description: "Unauthorized - missing or invalid JWT token"
        "500":
          description: "Internal server error"

  /wallets/{wallet}/codes:
    post:
      tags:
        - "Wallet"
      summary: "Activate a code"
      description: "Activates a promotional code for a wallet"
      security:
        - BearerAuth: []
      parameters:
        - name: "wallet"
          in: "path"
          required: true
          description: "Wallet address"
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActivateCodeRequest"
      responses:
        "200":
          description: "Code activated successfully"
        "400":
          description: "Bad request - invalid wallet address or code"
        "401":
          description: "Unauthorized - missing or invalid JWT token"
        "409":
          description: "Conflict - code not found or already used"
        "500":
          description: "Internal server error"

  /tracks/mints:
    post:
      tags:
        - "Tracks"
        - "Admin"
      summary: "Create mint tracking"
      description: "Configures tracking for NFT mint events (admin only)"
      security:
        - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMintTrackingRequest"
      responses:
        "201":
          description: "Mint tracking created successfully"
        "400":
          description: "Bad request - invalid input"
        "401":
          description: "Unauthorized - missing API key"
        "403":
          description: "Forbidden - invalid API key"
        "500":
          description: "Internal server error"
    get:
      tags:
        - "Tracks"
      summary: "List mint trackings"
      description: "Retrieves all configured mint trackings"
      responses:
        "200":
          description: "Mint trackings retrieved successfully"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MintTracking"
        "500":
          description: "Internal server error"

  /tracks/stakes:
    post:
      tags:
        - "Tracks"
        - "Admin"
      summary: "Create stake tracking"
      description: "Configures tracking for stake events (admin only)"
      security:
        - ApiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStakeTrackingRequest"
      responses:
        "201":
          description: "Stake tracking created successfully"
        "400":
          description: "Bad request - invalid input"
        "401":
          description: "Unauthorized - missing API key"
        "403":
          description: "Forbidden - invalid API key"
        "500":
          description: "Internal server error"
    get:
      tags:
        - "Tracks"
      summary: "List stake trackings"
      description: "Retrieves all configured stake trackings"
      responses:
        "200":
          description: "Stake trackings retrieved successfully"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StakeTracking"
        "500":
          description: "Internal server error"