import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { headers } from "next/headers";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { type Metadata } from "next";

import "./globals.css";
import { TanstackProvider } from "@/components/providers/Tanstack.provider";
import WagmiContextProvider from "@/components/providers/Wagmi.provider";
import { WalletProvider } from "@/components/providers/Wallet.provider";
import { CustomCursor } from "@/components/shared/UI/Cursor/CustomCursor";


const tusker_grotesk = localFont({
  src: [
    // Medium
    {
      path: "./_fonts/TuskerGrotesk-3500Medium.ttf",
      weight: "500",
      style: "normal",
    },
    // SemiBold
    {
      path: "./_fonts/TuskerGrotesk-3600Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    // Bold
    {
      path: "./_fonts/TuskerGrotesk-3700Bold.ttf",
      weight: "700",
      style: "normal",
    },
    // Super
    {
      path: "./_fonts/TuskerGrotesk-3800Super.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-tusker",
});

const tusker_grotesk_exp = localFont({
  src: [
    // Medium
    {
      path: "./_fonts/TuskerGrotesk-4500Medium.ttf",
      weight: "500",
      style: "normal",
    },
    // SemiBold
    {
      path: "./_fonts/TuskerGrotesk-4600Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    // Bold
    {
      path: "./_fonts/TuskerGrotesk-4700Bold.ttf",
      weight: "700",
      style: "normal",
    },
    // Super
    {
      path: "./_fonts/TuskerGrotesk-4800Super.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-tusker-exp",
});

const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = (await headers()).get("cookie");

  return (
    <html lang="en">
      <SpeedInsights />
      <TanstackProvider>
        <WagmiContextProvider cookies={cookies}>
          <WalletProvider>
            <body
              className={`${geistInter.variable} ${tusker_grotesk_exp.variable} ${tusker_grotesk.variable} antialiased`}
            >
              <CustomCursor />
              {children}
            </body>
          </WalletProvider>
        </WagmiContextProvider>
      </TanstackProvider>
    </html>
  );
}
